apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-dashboard
  template:
    metadata:
      labels:
        app: solar-dashboard
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: solar-dashboard
        image: mhefner1983/solar-dashboard:latest
        ports:
        - containerPort: 80
