apiVersion: v1
kind: Service
metadata:
  name: solar-dashboard
spec:
  type: NodePort
  selector:
    app: solar-dashboard
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30084  # You can pick any free port between 30000–32767
