apiVersion: v1
kind: Service
metadata:
  name: cpap-analyzer
spec:
  type: NodePort
  selector:
    app: cpap-analyzer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can pick any free port between 30000–32767
