apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-dashboard
spec:
  template:
    spec:
      containers:
        - name: solar-dashboard
          image: mhefner1983/solar-dashboard:latest  # tag it differently for dev
          imagePullPolicy: Always
